version: '3.8'
services:
  backend:
    build:
      context: ./emanuele-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/dev.db
    restart: unless-stopped
  frontend:
    build: ./marco-frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
networks:
  default:
    driver: bridge
