name: Create Issues from CSV

on:
  workflow_dispatch:
    inputs:
      csv_path:
        description: 'Path to CSV file'
        required: true
        default: '42_transcendence_github_project.csv'

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files and show CSV contents
        run: |
          ls -l
          cat ${{ github.event.inputs.csv_path }}

      - name: Check gh CLI version and auth
        run: |
          gh --version
          gh auth status

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas

      - name: Create issues from CSV with debug
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python <<EOF
          import pandas as pd
          import subprocess

          csv_file = '${{ github.event.inputs.csv_path }}'
          df = pd.read_csv(csv_file)

          for i, row in df.iterrows():
              title = row['Title']
              assignee = row['Assignee'] if pd.notna(row['Assignee']) else ""
              labels = row['Labels'] if pd.notna(row['Labels']) else ""
              body = f"**Target Date**: {row['Target Date']}\n\n**Status**: {row['Status']}"
              print(f"Creating issue #{i+1}: {title} assigned to '{assignee}' with labels '{labels}'")
              cmd = [
                  'gh', 'issue', 'create',
                  '--title', title,
                  '--body', body,
              ]
              if assignee:
                  cmd.extend(['--assignee', assignee])
              if labels:
                  cmd.extend(['--label', labels])
              print("Running command:", " ".join(cmd))
              subprocess.run(cmd)
          EOF
